services:
  nginx:
    build:
      context: ./react-vite
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - internal

  php:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel/:/var/www/html/
    networks:
      - internal

networks:
  internal:
    driver: bridge
