services:
  nginx:
    build:
      context: .
      dockerfile: react-vite/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - internal

  php:
    build:
      context: .
      dockerfile: laravel/Dockerfile
    volumes:
      - ./laravel/:/var/www/html/
    networks:
      - internal

networks:
  internal:
    driver: bridge
